name: Push-Actions

on: [push]

jobs:
  hello-world:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line PowerShell script
      run: |
        ./show-notification.ps1