name: Push-Actions

on: [push]

jobs:
  hello-world:

    runs-on: windows-latest

    steps:
    - name: Run a multi-line PowerShell script
      run: |
        Write-Host Sending email...
        ./get-date.ps1
